### ISSUE TITLE
Requires Python >=3.10

### ISSUE THREAD

**Issue by kaylai** [savioxavier/pyboxen#1]
Not an "issue" but a question. I see that pyboxen requires Python >=3.10. I'm not quite ready to update some of my code to 3.10, and I'm just wondering if this is a requirement for a reason or if pyboxen would work with, say, Python 3.9? If not, I'll just have to wait until I'm ready to upgrade everything :) Thanks!

**Comment by savioxavier** [comment]
Ah, looks Poetry decided to use my current Python version of 3.10 in there.

Could you check it right now? I have changed the minimum Python version to 3.8. Although Rich requires a minimum of 3.7 only, I decided to play it safe and use 3.8 instead.

I have released a patch version 1.1.1. Probably should work, though I was unable to test it out.

```sh-session
pip install -U pyboxen
```

**Comment by kaylai** [comment]
Working now, thank you!
